# Generated by Django 3.2.3 on 2021-05-15 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, validators=[django.core.validators.URLValidator])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categorymodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.providermodel')),
            ],
        ),
    ]
