# Generated by Django 3.2.3 on 2021-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='providercategorymodel',
            options={'verbose_name': 'Provider Category', 'verbose_name_plural': 'Provider Categories'},
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
