# Generated by Django 3.2.3 on 2021-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210523_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercategorymodel',
            name='url',
            field=models.URLField(),
        ),
    ]
