# Generated by Django 3.2.3 on 2021-05-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='providerproductmodel',
            options={'verbose_name': 'Provider Product', 'verbose_name_plural': 'Provider Products'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='name',
        ),
    ]
