# Generated by Django 3.2.3 on 2021-05-30 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210523_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerproductmodel',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providerproductmodel',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
