version: "3.9"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    restart: always

  django:
    build: ../
    env_file:
      - ../.env
    working_dir: /app/src
    command: sh -c "python manage.py runserver 0.0.0.0:8070"
    volumes:
      - ../:/app
    entrypoint:
      - /app/docker/backend/wait_for_postgres.sh
      - /app/docker/backend/entrypoint.sh
    ports:
      - "8070:8070"
    depends_on:
      - postgres

volumes:
  postgres_data: