# Generated by Django 3.2.4 on 2021-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_usermodel_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("RU", "Russian"), ("EN", "English"), ("BY", "Belarusian")],
                max_length=20,
                null=True,
            ),
        ),
    ]
